name: sqmvscreen
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiohttp
  - aiosignal
  - ambertools
  - annotated-types
  - anyio
  - aom
  - argon2-cffi
  - argon2-cffi-bindings
  - arpack
  - arrow
  - asttokens
  - astunparse
  - async-lru
  - async-timeout
  - attrs
  - babel
  - beautifulsoup4
  - biopandas
  - bleach
  - blosc
  - brotli
  - brotli-bin
  - brotli-python
  - bson
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - colorama
  - comm
  - contourpy
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cudatoolkit
  - cycler
  - dav1d
  - debugpy
  - decorator
  - defusedxml
  - dill
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - fftw
  - filelock
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freetype-py
  - fribidi
  - frozenlist
  - fsspec
  - gettext
  - gettext-tools
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - greenlet
  - h11
  - h2
  - harfbuzz
  - hdf4
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libasprintf
  - libasprintf-devel
  - libass
  - libblas
  - libboost
  - libboost-python
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libexpat
  - libffi
  - libgcc-ng
  - libgettextpo
  - libgettextpo-devel
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libhwloc
  - libiconv
  - libidn2
  - libjpeg-turbo
  - liblapack
  - libnetcdf
  - libnghttp2
  - libnpp
  - libnsl
  - libnvjpeg
  - libopenblas
  - libopenvino
  - libopenvino-auto-batch-plugin
  - libopenvino-auto-plugin
  - libopenvino-hetero-plugin
  - libopenvino-intel-cpu-plugin
  - libopenvino-intel-gpu-plugin
  - libopenvino-intel-npu-plugin
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - libopenvino-paddle-frontend
  - libopenvino-pytorch-frontend
  - libopenvino-tensorflow-frontend
  - libopenvino-tensorflow-lite-frontend
  - libopus
  - libpciaccess
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libtorch
  - libunistring
  - libuuid
  - libuv
  - libva
  - libvpx
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - lightning
  - lightning-utilities
  - lxml
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mda-xdrlib
  - mdtraj
  - mistune
  - mpc
  - mpfr
  - mpmath
  - multidict
  - munkres
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf-fortran
  - nettle
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - ocl-icd
  - ocl-icd-system
  - openff-amber-ff-ports
  - openff-forcefields
  - openff-interchange
  - openff-interchange-base
  - openff-models
  - openff-toolkit
  - openff-toolkit-base
  - openff-units
  - openff-utilities
  - openh264
  - openjpeg
  - openmm
  - openmmforcefields
  - openssl
  - overrides
  - p11-kit
  - packaging
  - pandarallel
  - pandas
  - pandocfilters
  - panedr
  - parmed
  - parso
  - pcre2
  - pdbfixer
  - perl
  - pexpect
  - pickleshare
  - pillow
  - pint
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pure_eval
  - py-cpuinfo
  - pycairo
  - pycparser
  - pydantic
  - pydantic-core
  - pyedr
  - pyg
  - pygments
  - pyparsing
  - pysocks
  - pytables
  - python
  - python-constraint
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytorch-cuda
  - pytorch-lightning
  - pytorch-mutex
  - pytz
  - pyyaml
  - pyzmq
  - rdkit
  - readline
  - referencing
  - reportlab
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rlpycairo
  - rpds-py
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - sleef
  - smirnoff99frosst
  - snappy
  - sniffio
  - soupsieve
  - sqlalchemy
  - stack_data
  - svt-av1
  - sympy
  - tbb
  - terminado
  - threadpoolctl
  - tinycss2
  - tinydb
  - tk
  - tomli
  - torchaudio
  - torchmetrics
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - unicodedata2
  - uri-template
  - urllib3
  - validators
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xmltodict
  - xorg-fixesproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - yarl
  - zeromq
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - amberutils
      - edgembar
      - mmpbsa-py
      - packmol-memgen
      - pdb4amber
      - pymsmt
      - pytraj
      - qupkake
      - sander
